
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 16 19:50:27 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 8;
  public static final int ASSIGNMENT = 28;
  public static final int SMALLER = 24;
  public static final int LPAREN = 38;
  public static final int GREATER = 22;
  public static final int SEMI = 31;
  public static final int CONTINUE = 14;
  public static final int FOR = 12;
  public static final int MINUS = 16;
  public static final int RPAREN = 39;
  public static final int AND = 26;
  public static final int OR = 27;
  public static final int COMMA = 32;
  public static final int SMALLER_EQUAL = 25;
  public static final int INC = 29;
  public static final int DIV = 18;
  public static final int PLUS = 15;
  public static final int IF = 10;
  public static final int LSQBRACE = 36;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int EQUAL = 20;
  public static final int GREATER_EQUAL = 23;
  public static final int NEW = 3;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 17;
  public static final int NUMBER = 42;
  public static final int MOD = 19;
  public static final int IDENT = 40;
  public static final int BREAK = 13;
  public static final int VOID = 9;
  public static final int LBRACE = 34;
  public static final int ELSE = 11;
  public static final int ENUM = 4;
  public static final int READ = 7;
  public static final int CHARCONST = 41;
  public static final int RBRACE = 35;
  public static final int BOOL_CONST = 43;
  public static final int RSQBRACE = 37;
  public static final int DEC = 30;
  public static final int PRINT = 6;
  public static final int UNEQUAL = 21;
}

